Handle errors more gracefully
The original version used wrong argument syntax in the crontab example
and also did not handle errors gracefully. A combination which lead to
failures without any hint what’s going on. The error output from OpenSSL
is captured and both the failing command and its error output are
printed if the certificate could not be checked.

diff --git a/ssl-cert-check b/ssl-cert-check
--- a/ssl-cert-check
+++ b/ssl-cert-check
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # vim: set fenc=utf-8:
 
-# Copyright (c) 2013, Rainer Müller <raimue@codingfarm.de>
+# Copyright (c) 2013-2014, Rainer Müller <raimue@codingfarm.de>
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -24,7 +24,7 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Version 2013-03-07
+# Version 2014-01-27
 # http://raim.codingfarm.de/blog/2013/03/07/checking-expiry-dates-of-local-and-remote-ssl-certificates/
 
 #### Usage ####
@@ -68,7 +68,7 @@
 #
 # Example for your crontab:
 #   MAILTO=root
-#   6       6    * * *   nobody /usr/local/bin/ssl-cert-check 30 /etc/apache2/ssl/*.crt /etc/ssl/certs/dovecot.pem https://localhost ssl://localhost:465 smtp+startssl://localhost:587
+#   6       6    * * *   nobody /usr/local/bin/ssl-cert-check 30 /etc/apache2/ssl/*.crt /etc/ssl/certs/dovecot.pem https://localhost ssl://localhost:465 smtp+starttls://localhost:587
 #
 #### #### ####
 
@@ -133,11 +133,25 @@ for cert in "$@"; do
             ;&
         ssl)
             # Retrieve certificate
-            certificate=$(echo | openssl s_client -connect "$target" $extra 2>/dev/null \
+            # Create new temporary file
+            tempfile=$(mktemp -t ssl-cert-check.XXXXX)
+            if [ -z "$tempfile" ]; then
+                echo "Error: unable to create temporary file" >&2
+                if [ $exitcode -lt 2 ]; then
+                    exitcode=2
+                fi
+                continue
+            fi
+            # Delete temporary file if shell exits during certificate check
+            trap "rm -f $tempfile" EXIT
+            cmd=(openssl s_client -connect "$target" $extra)
+            certificate=$(echo | ${cmd[@]} 2>$tempfile \
                 | sed -n -e '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' \
                     -e '/-----END CERTIFICATE-----/q')
             if [ "$certificate" == "" ]; then
                 echo "Error: unable to check $cert" >&2
+                echo "Error: command was '${cmd[@]}', openssl error messages were:" >&2
+                sed 's/^/    /' $tempfile >&2
                 if [ $exitcode -lt 2 ]; then
                     exitcode=2
                 fi
@@ -146,6 +160,7 @@ for cert in "$@"; do
                 # Extract notAfter date of validity
                 enddate=$(echo "$certificate" | openssl x509 -checkend $(( 86400 * $DAYS )) -enddate)
             fi
+            rm -f $tempfile
             ;;
     esac
 
