Allow to pass parameters as a file

diff --git a/ssl-cert-check b/ssl-cert-check
--- a/ssl-cert-check
+++ b/ssl-cert-check
@@ -28,6 +28,11 @@
 # https://raim.codingfarm.de/blog/tag/ssl-cert-check/
 # https://github.com/raimue/ssl-cert-check
 
+if [ $BASH_VERSINFO -lt 4 ]; then
+    echo "Error: this script requires bash >= 4.0" >&2
+    exit 3
+fi
+
 # First parameter specifies if certificate expire in the next X days
 DAYS=$1
 shift
@@ -37,9 +42,14 @@ if [[ ! $DAYS =~ ^[0-9]+$ ]]; then
     exit 3
 fi
 
-if [ $BASH_VERSINFO -lt 4 ]; then
-    echo "Error: this script requires bash >= 4.0" >&2
-    exit 3
+if [[ "$1" == --list=* ]]; then
+    LIST=${1##--list=}
+    if [[ ! -r "$LIST" ]]; then
+        echo "Error: list is not a regular file" >&2
+    fi
+    readarray -t TARGETS < "$LIST"
+else
+    TARGETS=("$@")
 fi
 
 # We need extended globbing
@@ -47,7 +57,7 @@ shopt -s extglob
 
 exitcode=0
 
-for cert in "$@"; do
+for cert in "${TARGETS[@]}"; do
     enddate=""
 
     # For ease of use, map any absolute path name to a file:// URL
