ShellCheck: SC2145
SC2145 Argument mixes string and array. Use * or separate argument.

https://github.com/koalaman/shellcheck/wiki/SC2145

diff --git a/ssl-cert-check b/ssl-cert-check
--- a/ssl-cert-check
+++ b/ssl-cert-check
@@ -119,7 +119,7 @@ for cert in "${TARGETS[@]}"; do
                     -e '/-----END CERTIFICATE-----/q')
             if [ "$certificate" == "" ]; then
                 echo "Error: unable to check $cert" >&2
-                echo "Error: command was '${cmd[@]}', openssl error messages were:" >&2
+                echo "Error: command was '${cmd[*]}', openssl error messages were:" >&2
                 sed 's/^/    /' $tempfile >&2
                 if [ $exitcode -lt 2 ]; then
                     exitcode=2
